export const initialNodes = [
  {
    id: '1',
    type: 'cloudNode',
    position: { x: 40, y: 80 },
    data: {
      label: 'AWS Account',
      subtitle: 'Cloud provider',
      iconKey: 'providers.aws',
      color: '#FF9900',
      group: 'prevention',
    },
  },
  {
    id: '2',
    type: 'cloudNode',
    position: { x: 320, y: 80 },
    data: {
      label: 'Security Hub',
      subtitle: 'Control plane',
      iconKey: 'awsServices.securityHub',
      color: '#2563EB',
      group: 'detection',
    },
  },
  {
    id: '3',
    type: 'cloudNode',
    position: { x: 620, y: 80 },
    data: {
      label: 'Lambda Remediation',
      subtitle: 'Auto-remediation',
      iconKey: 'awsServices.lambda',
      color: '#7C3AED',
      group: 'response',
    },
  },
  {
    id: '4',
    type: 'cloudNode',
    position: { x: 940, y: 80 },
    data: {
      label: 'SOC / Slack',
      subtitle: 'Alerting and triage',
      iconKey: 'securityPlatforms.slack',
      color: '#E11D48',
      group: 'response',
    },
  },
  {
    id: '5',
    type: 'cloudNode',
    position: { x: 320, y: 240 },
    data: {
      label: 'GuardDuty',
      subtitle: 'Threat detection',
      iconKey: 'awsServices.guardDuty',
      color: '#F59E0B',
      group: 'detection',
    },
  },
  {
    id: '6',
    type: 'cloudNode',
    position: { x: 620, y: 240 },
    data: {
      label: 'SIEM / XDR',
      subtitle: 'Correlation',
      iconKey: 'securityPlatforms.splunk',
      color: '#0F766E',
      group: 'detection',
    },
  },
  {
    id: '7',
    type: 'cloudNode',
    position: { x: 40, y: 400 },
    data: {
      label: 'Azure Subscription',
      subtitle: 'Cloud provider',
      iconKey: 'providers.azure',
      color: '#0078D4',
      group: 'prevention',
    },
  },
  {
    id: '8',
    type: 'cloudNode',
    position: { x: 320, y: 400 },
    data: {
[O      label: 'Defender for Cloud',
      subtitle: 'Posture and alerts',
      iconKey: 'azureServices.defenderForCloud',
      color: '#0284C7',
      group: 'detection',
    },
  },
  {
    id: '9',
    type: 'cloudNode',
    position: { x: 620, y: 400 },
    data: {
      label: 'Microsoft Sentinel',
      subtitle: 'SIEM / SOAR',
      iconKey: 'azureServices.sentinel',
      color: '#4338CA',
      group: 'response',
    },
  },
  {
    id: '10',
    type: 'cloudNode',
    position: { x: 40, y: 560 },
    data: {
      label: 'GCP Project',
      subtitle: 'Cloud provider',
      iconKey: 'providers.gcp',
      color: '#4285F4',
      group: 'prevention',
    },
  },
  {
    id: '11',
    type: 'cloudNode',
    position: { x: 320, y: 560 },
    data: {
      label: 'Security Command Center',
      subtitle: 'Central findings',
      iconKey: 'gcpServices.securityCommandCenter',
      color: '#1D4ED8',
      group: 'detection',
    },
  },
  {
    id: '12',
    type: 'cloudNode',
    position: { x: 620, y: 560 },
    data: {
      label: 'Cortex Cloud / CNAPP',
      subtitle: 'Unified visibility',
      iconKey: 'securityPlatforms.paloAlto',
      color: '#EA580C',
      group: 'detection',
    },
  },
  {
    id: '13',
    type: 'cloudNode',
    position: { x: 940, y: 320 },
    data: {
      label: 'Kubernetes',
      subtitle: 'Runtime platform',
      iconKey: 'containerDevSecOps.kubernetes',
      color: '#2563EB',
      group: 'prevention',
    },
  },
  {
    id: '14',
    type: 'cloudNode',
    position: { x: 1180, y: 320 },
    data: {
      label: 'GitHub Actions',
      subtitle: 'CI/CD security',
      iconKey: 'containerDevSecOps.github',
      color: '#111827',
      group: 'prevention',
    },
  },
  {
    id: '15',
    type: 'cloudNode',
    position: { x: 1180, y: 120 },
    data: {
      label: 'Terraform',
      subtitle: 'Infrastructure as Code',
      iconKey: 'containerDevSecOps.terraform',
      color: '#7C3AED',
      group: 'prevention',
    },
  },
];

export const initialEdges = [
  { id: 'e1-2', source: '1', target: '2', animated: true, label: 'Centralize findings' },
  { id: 'e1-5', source: '1', target: '5', animated: true, label: 'Threat telemetry' },
  { id: 'e5-2', source: '5', target: '2', animated: true, label: 'Aggregate' },
  { id: 'e2-3', source: '2', target: '3', animated: true, label: 'Remediate' },
  { id: 'e2-6', source: '2', target: '6', animated: true, label: 'Forward to SIEM' },
  { id: 'e6-4', source: '6', target: '4', animated: true, label: 'Notify SOC' },

  { id: 'e7-8', source: '7', target: '8', animated: true, label: 'Assess posture' },
  { id: 'e8-9', source: '8', target: '9', animated: true, label: 'Escalate incidents' },
  { id: 'e9-4', source: '9', target: '4', animated: true, label: 'Analyst workflow' },

  { id: 'e10-11', source: '10', target: '11', animated: true, label: 'Collect findings' },
  { id: 'e11-12', source: '11', target: '12', animated: true, label: 'Correlate posture' },
  { id: 'e12-4', source: '12', target: '4', animated: true, label: 'Alert ops' },

  { id: 'e13-12', source: '13', target: '12', animated: true, label: 'Runtime signals' },
  { id: 'e14-15', source: '14', target: '15', animated: true, label: 'Pipeline' },
  { id: 'e15-1', source: '15', target: '1', animated: true, label: 'Provision AWS' },
];
